### ISSUE TITLE
Process is exiting when an invalid key is used with `on`

### ISSUE THREAD

**Issue by parruda** [gotta-dev/gotta-mod#5]
When using an invalid key like:

```
on :foo do |event|
  ...
end
```

The process is exiting. The correct behaviour should be to raise an exception.
Valid keys are: `:added`, `:modified`, `:removed`, `:deleted` and `:all`.
(@tylerklose would you like to add any other valid key?)

**Comment by tylerklose** [comment]
@parruda not sure, but I want to question whether or not `:modified` is accurate. It seems like it’s more like `:saved`. 

An aside: should these events be written in the past tense?
```ruby
on :added, :modified do |event|
  ...
end
```
vs.
```ruby
on :add, :modify do |event|
  ...
end
```

**Comment by parruda** [comment]
> @parruda not sure, but I want to question whether or not :modified is accurate. It seems like it’s more like :saved.
`:modified`, `:changed` and `:saved` should be supported.

> An aside: should these events be written in the past tense?
I think so. Usually you act on an event that already happened.

**Comment by parruda** [comment]
Just to summarize the events:

* When there's a new file: `:added`, `:created`
* When a file has changed: `:modified`, `:changed`, `:saved`
* When a file is removed: `:removed`, `:deleted`

**Comment by tylerklose** [comment]
> I think so. Usually you act on an event that already happened. Maybe there's a better word instead of on that will make it read a bit better?

How about `when`?

```ruby
when :added, :modified, :changed do |event|
  ...
end
```

But this doesn't work for `:all`.
```ruby
when :all do |event|
  ...
end
```

But now that I think about it.. `:all` is dangerous. What if we implement a new event type that a user doesn't want. For example: I want to use `:added`, `:changed`, `:deleted` and as of right this very moment... that's synonymous with `:all`. But now we decide to implement `on :renamed`. `on :all` would also pick up `:renamed`, but that may or may not be desired. Seems like `:all` could potentially lead to shooting ourselves in the foot?

**Comment by parruda** [comment]
`when` is a protected word on Ruby. Can't use it :(

> But now we decide to implement on :renamed

I don't think we will be able implement `on :renamed` in a performant way. A rename fires 2 events: `:added` and `:removed`.

**Comment by tylerklose** [comment]
@parruda `:renamed` was a hypothetical event we invent in the future! The actual event implemented isn't important, but the implication of us introducing a new event and a mod using `:all` somewhere is critical

**Comment by tylerklose** [comment]
On the `on` vs. `when` vs. an alternative, we can keep `on` if the events are in the present tense and it should read nicely.

```ruby
on :delete do |event|
  ...
end
```

```ruby
on :add do |event|
  ...
end
```

```ruby
on :modify do |event|
  ...
end
```

I thought about using `file` as well with the past tense:
```ruby
file :deleted do |event|
  ...
end
```

```ruby
file :added do |event|
  ...
end
```

```ruby
file :modified do |event|
  ...
end
```

**Comment by parruda** [comment]
I like `file`. I will open an issue for the change.

**Comment by parruda** [comment]
`file` vs `on` conversation moved to #8
